# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-26 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='Celular',
            field=models.CharField(max_length=14),
        ),
    ]
