# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-07 18:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190726_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='Data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 7, 18, 10, 0, 99794)),
        ),
    ]
