# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-09 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190808_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='Data',
            field=models.DateField(blank=True),
        ),
    ]
