# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-12 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190810_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='Age',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='contato',
            name='Data',
            field=models.DateField(blank=True),
        ),
    ]
