# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-13 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import polls.validators


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190812_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='Email',
            field=models.EmailField(max_length=254, null=True, validators=[polls.validators.validate_school_email]),
        ),
    ]
