# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-14 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190813_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='Age',
        ),
    ]
