# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-14 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import polls.validators


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_contato_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='Data',
            field=models.DateField(blank=True, validators=[polls.validators.validate_year_birtday]),
        ),
    ]
