# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-15 12:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0010_auto_20190814_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='donoDaAgenda',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
