# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-15 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_contato_donodaagenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='donoDaAgenda',
            new_name='donosDeAgenda',
        ),
    ]
