# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-15 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_contato_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
