# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-15 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_contato_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='cpf',
        ),
    ]
