# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-05 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0017_contato_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='niveis',
            name='perfil',
            field=models.ManyToManyField(related_name='profissionais', to='polls.Perfil'),
        ),
        migrations.AddField(
            model_name='niveis',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profissional', to=settings.AUTH_USER_MODEL),
        ),
    ]
