# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-05 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20190905_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niveis',
            name='nome',
        ),
    ]
