# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-08 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_remove_niveis_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niveis',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='niveis',
            name='user',
        ),
        migrations.AddField(
            model_name='contato',
            name='perfil',
            field=models.ManyToManyField(related_name='profissionais', to='polls.Perfil'),
        ),
        migrations.DeleteModel(
            name='Niveis',
        ),
    ]
