# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-08 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20190908_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='perfil',
            field=models.ManyToManyField(default='basico', related_name='profissionais', to='polls.Perfil'),
        ),
    ]
