# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-08 03:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0021_auto_20190908_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('perfil', models.ManyToManyField(related_name='nivel', to='polls.Perfil')),
            ],
        ),
        migrations.RemoveField(
            model_name='contato',
            name='perfil',
        ),
    ]
